### ISSUE TITLE
StableDiffusion / Non-zero status code returned while running Add node. Name:'Add_221'

### ISSUE THREAD

**Issue by imranypatel** [saddam213/OnnxStack#142]
While trying Basic Stable Diffusion Example of https://www.nuget.org/packages/OnnxStack.StableDiffusion, at the following line in the code:

```
    // Run Pipleine
    var result = await pipeline.GenerateImageAsync(promptOptions);
```

Following exception is raised:

```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:RuntimeException] Non-zero status code returned while running Add node. Name:'Add_221' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2482)\onnxruntime.DLL!00007FFC280E7AA5: (caller: 00007FFC280E712D) Exception(3) tid(1b6c) 80004005 Unspecified error

  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.<>c__DisplayClass75_0.<RunAsync>b__0(IReadOnlyCollection`1 outputs, IntPtr status)
--- End of stack trace from previous location ---
   at Microsoft.ML.OnnxRuntime.InferenceSession.<RunAsync>d__75.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<EncodePromptTokensAsync>d__39.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<GeneratePromptEmbedsAsync>d__40.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<CreatePromptEmbedsAsync>d__37.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<RunInternalAsync>d__31.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<GenerateImageAsync>d__26.MoveNext()
   at TestOnnxStack.TestStableDiffusion.<Test01>d__1.MoveNext() in ...\TestOnnxStack\TestStableDiffusion.cs:line 42
   at Program.<<Main>$>d__0.MoveNext() in ...i\TestOnnxStack\Program.cs:line 6

```

**To reproduce:**

1. Create .net8 console project
2. Add nuget package microsoft.ml.onnxruntime.directml (1.17.3) and onnxstack.stablediffusion (0.31.0)
3. Copy code in Program.cs from Basic Stable Diffusion Example of https://www.nuget.org/packages/OnnxStack.StableDiffusion documentation.
4. create d:\model folder to git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 -b onnx
5. change path to model in code e.g. var pipeline = StableDiffusionPipeline.CreatePipeline(@"D:\model\stable-diffusion-v1-5");

**Platform**

- Windows 10
- .NET 8.0.200
- OnnxStack.StableDiffusion 0.31.0
- Microsoft.ML.OnnxRuntime.DirectML Version="1.17.3"
- Target CPU x64

**Comment by saddam213** [comment]
That;s an odd looking error coming from deep within

I'll download that model and see if its a regression, been a while since I have used the version of the model

I have this version on disk, and taht seems to work ok following your steps
https://huggingface.co/TensorStack/stable-diffusion-v1-5-onnx

I will check the other model now and update you with what I find

**Comment by imranypatel** [comment]
Downloaded the model from https://huggingface.co/TensorStack/stable-diffusion-v1-5-onnx

Now getting slightly different error than above:

```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:RuntimeException] Non-zero status code returned while running Mul node. Name:'' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2482)\onnxruntime.DLL!00007FFC9DD77AA5: (caller: 00007FFC9DD7712D) Exception(3) tid(6c74) 80004005 Unspecified error

  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.<>c__DisplayClass75_0.<RunAsync>b__0(IReadOnlyCollection`1 outputs, IntPtr status)
--- End of stack trace from previous location ---
   at Microsoft.ML.OnnxRuntime.InferenceSession.<RunAsync>d__75.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<EncodePromptTokensAsync>d__39.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<GeneratePromptEmbedsAsync>d__40.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<CreatePromptEmbedsAsync>d__37.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<RunInternalAsync>d__31.MoveNext()
   at OnnxStack.StableDiffusion.Pipelines.StableDiffusionPipeline.<GenerateImageAsync>d__26.MoveNext()
   at TestOnnxStack.TestStableDiffusion.<Test01>d__1.MoveNext() in ...\TestOnnxStack\TestStableDiffusion.cs:line 42
   at Program.<<Main>$>d__0.MoveNext() in ...i\TestOnnxStack\Program.cs:line 6
```

**Device/CPU.:**

![image](https://github.com/saddam213/OnnxStack/assets/4316514/7cdec32b-74b8-46b7-81f4-0bb0f5c3a4d2)

**GPU:**
![image](https://github.com/saddam213/OnnxStack/assets/4316514/8de5a584-7a2a-462e-bee8-3c0cb85b06b5)

![image](https://github.com/saddam213/OnnxStack/assets/4316514/5c20b91b-9d3b-4e6b-9d03-fe08178697f6)


Kind of stuck at the moment as just a beginner in this ML.Net/Onnx/directML/etc. space.

Thank you for your support.

**Comment by saddam213** [comment]
Unfortunately you GPU may not have enough VRAM for stable diffusion, and minimum you would need 3GB-4GB for a F16 model

You can switch to CPU mode by using the CPU execution provider and see if that works

`var pipeline = StableDiffusionPipeline.CreatePipeline(@"D:\models\test\stable-diffusion-v1-5", executionProvider: ExecutionProvider.Cpu);`

Its ok, I'm just learning ML too :)

**Comment by imranypatel** [comment]
Tried on another machine with success. 

Typical GPU state during image generation:
![image](https://github.com/saddam213/OnnxStack/assets/4316514/262c91d7-a67e-4f19-8bb1-81a267ced3ca)

Dxdiag system:
![image](https://github.com/saddam213/OnnxStack/assets/4316514/bee5df81-6f5a-45ab-bc41-3ac9c55d0949)

Dxdiage AMD Radeon GPU:
![image](https://github.com/saddam213/OnnxStack/assets/4316514/061c3453-d455-40fe-8a95-1c873eda8652)

It takes on average about 8 minutes per image generation.

Now looking into how to reduce the time, which is of course not accetable at the moment.

Would welcome any suggestion in that direction!
