### ISSUE TITLE
fails when loading model

### ISSUE THREAD

**Issue by yggdrasil75** [saddam213/OnnxStack#92]
[1/5/2024 8:57:40 AM] [Information] [ModelPickerControl] [LoadModel] - 'dreamlike' Loaded., Elapsed: 3ms
[1/5/2024 8:57:43 AM] [Information] [ModelPickerControl] [LoadModel] - 'dreamlike' Loading...
[1/5/2024 8:57:43 AM] [Error] [ModelPickerControl] An error occured while loading model 'dreamlike' 
 Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\non-docker\OnnxStack_TensorRT\onnxruntime_providers_tensorrt.dll"

   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_Tensorrt(Int32 deviceId)
   at OnnxStack.Core.Extensions.GetSessionOptions(OnnxModelConfig configuration)
   at OnnxStack.Core.Model.OnnxModelSession..ctor(OnnxModelConfig configuration, PrePackedWeightsContainer container)
   at OnnxStack.Core.Model.OnnxModelSet.<.ctor>b__3_1(OnnxModelConfig modelConfig)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource element)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at OnnxStack.Core.Model.OnnxModelSet..ctor(IOnnxModelSetConfig configuration)
   at OnnxStack.Core.Services.OnnxModelService.LoadModelSet(IOnnxModelSetConfig modelSetConfig)
   at OnnxStack.Core.Services.OnnxModelService.<>c__DisplayClass5_0.<LoadModelAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at OnnxStack.Core.Services.OnnxModelService.LoadModelAsync(IOnnxModelSetConfig model)
   at OnnxStack.StableDiffusion.Services.StableDiffusionService.LoadModelAsync(IOnnxModelSetConfig model)
   at OnnxStack.UI.UserControls.ModelPickerControl.LoadModel() in D:\Repositories\OnnxStack\OnnxStack.UI\UserControls\ModelPickerControl.xaml.cs:line 124
[1/5/2024 8:57:43 AM] [Information] [ModelPickerControl] [LoadModel] - 'dreamlike' Loaded., Elapsed: 3ms

I downloaded the huggingface repo in the readme and attempted to load, but get this in the logs.
I will note: this is looking for a file on the drive d, instead of a file in the download. I believe you may have fixed paths instead of relative paths in your repo.

**Comment by jeffward01** [comment]
Are you running this from `OnnxStack.Console`?  

It sounds like you need to update the paths to your models in the `appsettings.json` file.   

Can you share more information about:

* What are you doing? Are you running the UI or the example console app?

**Comment by saddam213** [comment]
Have you `installed` all the correct dependencies for the `TensorRT` version?

The error `LoadLibrary failed with error 126 ` indicates that `OnnxRuntime` can't find one of the `CUDA` or `TensorRT` libraries.

The `Cuda` and `TensorRT` builds are experimental but do work, however you need to install a lot of `Cuda` dependencies
Name| ONNX EP| Device | Requirements | Status
--- | --- | --- | --- | --- |
OnnxStack_UI.zip|DirectML| CPU, AMD GPU, Nvidia GPU| At least Windows10| Stable
OnnxStack_UI_Cuda.zip|CUDA| CPU, Nvidia GPU| `CUDA 11`  and `cuDNN` toolkit| Experimental
OnnxStack_UI_TensorRT.zip|TensorRT| CPU, Nvidia GPU| `CUDA 11` , `cuDNN` and TensorRT libraries| Experimental

I would recommend the DirectML default build as its more compatible 

Links to the things that need to be installed for `TensorRT` if you would like.
`CUDA 11` - https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
`CUDNN` - https://developer.nvidia.com/cudnn
`TensortRT` https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by saddam213** [comment]
There are no instructions for the UI because its just a simple example app

Unfortunately this library may not be compatible with your card, its still new and does not have many testers
